# -*- coding: utf-8 -*-
"""grade-checker-Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k6kxOueb3Zlx985Yhk92qdeT9R8fzpcU
"""

check_num = int(input("Enter your value : "))
print("Your value is : ",check_num)
match check_num:
  case n if n>=80 and n<100:
    print("A+")
  case n if n>=70 and n<=80:
    print("Your grade is A ")
  case n if n>60 and n<70:
    print("Your grade is B ")
  case n if n>50 and n<60:
    print("Your grade is C ")
  case _:
    print("sorry Fail")